# Generated by Django 5.1 on 2024-08-26 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('BS', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('MS', 'Master of Science'), ('MA', 'Master of Arts'), ('PHD', 'Doctor of Philosophy'), ('OTHER', 'Other')], max_length=5)),
                ('major', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('application_round', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('INTERVIEW', 'Interview Invite')], max_length=10)),
                ('notification_method', models.CharField(max_length=20)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('gpa_scale', models.FloatField(default=4.0)),
                ('test_type', models.CharField(blank=True, max_length=20, null=True)),
                ('test_score', models.IntegerField(blank=True, null=True)),
                ('student_type', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International')], max_length=13)),
                ('continent', models.CharField(blank=True, choices=[('AF', 'Africa'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('SA', 'South America'), ('OC', 'Oceania'), ('AN', 'Antarctica')], max_length=2, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('financial_aid', models.BooleanField(default=False)),
                ('scholarship', models.CharField(blank=True, max_length=100, null=True)),
                ('post_grad_plans', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
