# Generated by Django 5.1 on 2024-08-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
